// ==UserScript==
// @name         bili-awsl
// @namespace    vite-plugin-monkey
// @version      1.0.5
// @author       yuanci222
// @description  Auto AWSLing for Bilibili
// @match        https://*.bilibili.com/*
// ==/UserScript==

(function () {
	'use strict';

	const o={player:"#bilibili-player",toolbar:".arc_toolbar_report",sharePanel:".share_dropdown",wideModeButton:".bpx-player-ctrl-wide",wideModeButtonActivated:"bpx-state-entered",barrageInput:".bpx-player-dm-input",barrageSendButton:".bpx-player-dm-btn-send",barrageSendingArea:".bpx-player-sending-area",adBlockTip:".adblock-tips",avatar:".header-entry-mini",leftEntry:".left-entry",downloadClientTrigger:".download-client-trigger"},s=(t,n)=>t.querySelector(n),h=(t,n)=>{const e={};for(const r in n){const a=s(t,n[r]);if(a==null)return null;e[r]=a;}return e},y=(t,n,e)=>(t.addEventListener(n,e,!1),t),v=(t,n)=>{for(const e in n)t.style.setProperty(e,n[e]);return t},l=(t,n=[],e)=>{const r=document.createElement(t);return n&&c(r,{class:x(n)}),e!=null&&e.attrs&&c(r,e.attrs),e!=null&&e.style&&v(r,e.style),e!=null&&e.html&&g(r,e.html),r},d=(t,n)=>{const e=new MutationObserver(n);return e.observe(t,{childList:!0,subtree:!0}),e},x=t=>t.join(" "),c=(t,n)=>{for(const e in n){const r=n[e];r==null?t.removeAttribute(e):t.setAttribute(e,r);}return t},g=(t,n)=>(t.innerHTML=n,t),i=(t,n)=>{const e=n();return t.append(e),e};d(document.body,()=>{const t=s(document,o.player);if(!t)return;const n=s(t,o.wideModeButton);n&&!n.className.includes(o.wideModeButtonActivated)&&n.click();});var b=(()=>typeof GM<"u"?GM:void 0)();const k="awsl;草",f={height:"28px","line-height":"28px","border-radius":"9999px",border:"none","font-size":"13px",padding:"0 12px","box-sizing":"border-box",transition:"all .3s",display:"inline-flex","-ms-flex-align":"center","align-items":"center",cursor:"pointer",color:"#ffffff"};d(document.body,async()=>{if(!s(document,o.player))return;const n=s(document,`${o.barrageSendingArea}:not([awsl="yes"])`);if(!n)return;const e=(await b.getValue("words",k)).split(";").filter(a=>!!a);B(n,e)&&c(n,{awsl:"yes"});});const B=(t,n)=>{const e=h(t,{textarea:o.barrageInput,submit:o.barrageSendButton});if(!e)return !1;const r=i(t,()=>l("div",[],{style:{display:"flex","flex-wrap":"wrap","align-items":"center",gap:"12px",padding:"12px",background:"#ffffff"}}));i(r,()=>C());for(const a of n){const u=i(r,()=>E(a));y(u,"click",()=>{e.textarea.value=a+e.textarea.value,e.textarea.dispatchEvent(new Event("input")),setTimeout(()=>{e.submit.click();},200);});}return !0},E=t=>{const n=l("button",["bui-button-blue"],{style:{...f,background:"var(--bpx-fn-color,#00a1d6)"}});return i(n,()=>l("span",["woo-button-content"],{html:t})),n},C=()=>{const t=l("button",[],{style:{...f,background:"var(--brand_pink, #FF6699)"}});return i(t,()=>l("span",["woo-button-content"],{html:"自定义/Customize"})),y(t,"click",async()=>{const n=await b.getValue("words",""),e=window.prompt(`输入多个短语，以 ; 分隔
Enter multiple phrases, separated by ";"`,n);e&&e.trim()!==""&&(await b.setValue("words",e),window.location.reload());}),t};d(document.body,()=>{const t=s(document,o.adBlockTip);t&&t.remove();});d(document.body,()=>{var m;const t=s(document,`${o.leftEntry}:not([awsl="yes"])`);if(!t)return;(m=t.lastElementChild)!=null&&m.querySelector(o.downloadClientTrigger)&&t.removeChild(t.lastElementChild);const n=s(document,o.avatar);if(!n||n.tagName.toUpperCase()!=="A")return;const r=n.href.split("/").pop();if(!r)return;const a=`https://space.bilibili.com/${r}/cinema`,u=l("li",["v-popover-wrap"]);i(u,()=>{const p=l("a",["default-entry",""]);c(p,{href:a,target:"_blank"});const w=document.documentElement.lang;return p.innerText=w==="zh-CN"?"追剧":"Cinema",p}),t.appendChild(u),c(t,{awsl:"yes"});});

})();